### ISSUE TITLE
Change Light Level Based On Time Of Day

### ISSUE THREAD

**Issue by randomPoison** [Capstrong/Godlands#130]
Right now the light level starts bright and never really dims. The light needs to start dimmer, get bright at midday, and then get dark again at night.

**Comment by brickman1444** [comment]
Move start of day to midday, adjust art to put sun on left side, change daylightIntensity function to be something like ( timeOfDay  + x ) ^ ( y ) where y < 1.

**Comment by cjacobwade** [comment]
This change is done in the render settings asset. Day setting's light intensity should be around 1, while night setting's light intensity should be around 0.2

**Comment by randomPoison** [comment]
@cjacobwade Have the render settings been updated with better values? If not I'd prefer to keep this issue open as a reminder to update them.
