### ISSUE TITLE
Better Resource Placement

### ISSUE THREAD

**Issue by randomPoison** [Capstrong/Godlands#33]
Right now resource spawner just spawns in a flat ring regardless of where the ground is. Objects spawned by the spawner should snap the ground, and they should always be over the ground (so if the  spawner is near a ledge it doesn't put spawners floating in the air).

**Comment by cjacobwade** [comment]
I put in a snap to ground thing at some point, although they can still end up floating.

**Comment by brickman1444** [comment]
The floating issue has been dealt with in #45 but they sometimes still spawn inside other objects. The current solution is that a gizmo is drawn around the spawners and the level designer has to keep it from intersecting other objects.

**Comment by randomPoison** [comment]
This isn't really an issue any more, or at least we're not going to do any more work on it.
